name = "vorlage0"
entladedatum = '08-02-2016'
rcsstatus = 'Archiviert'

[version]

  [version.aktuell]
  v = 0.0
  letzetesCheckinVon = 'trautear'
  beschreibung = '''Notiz zur Version. Darf über mehrere Zeilen gehen'''

  [version.produktiv]
  v = 0.0
  letzetesCheckinVon = 'trautear'
  beschreibung = '''Notiz zur Version. Darf über mehrere Zeilen gehen'''
