name = "vorlage1"
entladedatum = '05-10-2015'
rcsstatus = 'Archiviert'

[version]

  [version.aktuell]
  v = 0.0
  letzetesCheckinVon = 'trautear'
  beschreibung = '''Notiz zur Version. Darf über mehrere Zeilen gehen'''

  [version.produktiv]
  v = 0.0
  letzetesCheckinVon = 'trautear'
  beschreibung = '''Notiz zur Version. Darf über mehrere Zeilen gehen'''
